title: Dhruv Aditya Srivastava, Ph.D.
#logo: /assets/img/headshot_circle.png
description: An interdisciplinary scientist with over 12 years of international research experience in molecular biology, microbiology, and plant science.
#show_downloads: true
theme: jekyll-theme-minimal
